# Generated by Django 4.0.4 on 2022-05-27 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dt3',
            table='dienthoai2',
        ),
    ]
