# Generated by Django 4.0.4 on 2022-05-27 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_dt3_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dt3',
            table='dienthoai1',
        ),
    ]
