# Generated by Django 4.0.4 on 2022-05-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_dt3_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dt1',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='name', null=True)),
                ('brand', models.TextField(blank=True, db_column='brand', null=True)),
                ('display', models.TextField(blank=True, db_column='display', null=True)),
                ('hdh', models.TextField(blank=True, db_column='hdh', null=True)),
                ('camera_sau', models.TextField(blank=True, db_column='camera_sau', null=True)),
                ('camera_truoc', models.TextField(blank=True, db_column='camera_truoc', null=True)),
                ('chip', models.TextField(blank=True, db_column='chip', null=True)),
                ('ram', models.TextField(blank=True, db_column='ram', null=True)),
                ('rom', models.TextField(blank=True, db_column='rom', null=True)),
                ('sim', models.TextField(blank=True, db_column='sim', null=True)),
                ('battery', models.TextField(blank=True, db_column='battery', null=True)),
                ('gia', models.IntegerField(blank=True, db_column='price', null=True)),
                ('danhgia', models.TextField(blank=True, db_column='danhgia', null=True)),
                ('soluong', models.IntegerField(blank=True, db_column='sluong', null=True)),
                ('link', models.TextField(blank=True, db_column='link', null=True)),
            ],
            options={
                'db_table': 'dienthoai1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dt2',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='name', null=True)),
                ('brand', models.TextField(blank=True, db_column='brand', null=True)),
                ('display', models.TextField(blank=True, db_column='display', null=True)),
                ('hdh', models.TextField(blank=True, db_column='hdh', null=True)),
                ('camera_sau', models.TextField(blank=True, db_column='camera_sau', null=True)),
                ('camera_truoc', models.TextField(blank=True, db_column='camera_truoc', null=True)),
                ('chip', models.TextField(blank=True, db_column='chip', null=True)),
                ('ram', models.TextField(blank=True, db_column='ram', null=True)),
                ('rom', models.TextField(blank=True, db_column='rom', null=True)),
                ('sim', models.TextField(blank=True, db_column='sim', null=True)),
                ('battery', models.TextField(blank=True, db_column='battery', null=True)),
                ('gia', models.IntegerField(blank=True, db_column='price', null=True)),
                ('danhgia', models.TextField(blank=True, db_column='danhgia', null=True)),
                ('soluong', models.IntegerField(blank=True, db_column='sluong', null=True)),
                ('link', models.TextField(blank=True, db_column='link', null=True)),
            ],
            options={
                'db_table': 'dienthoai2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dt4',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='name', null=True)),
                ('brand', models.TextField(blank=True, db_column='brand', null=True)),
                ('display', models.TextField(blank=True, db_column='display', null=True)),
                ('hdh', models.TextField(blank=True, db_column='hdh', null=True)),
                ('camera_sau', models.TextField(blank=True, db_column='camera_sau', null=True)),
                ('camera_truoc', models.TextField(blank=True, db_column='camera_truoc', null=True)),
                ('chip', models.TextField(blank=True, db_column='chip', null=True)),
                ('ram', models.TextField(blank=True, db_column='ram', null=True)),
                ('rom', models.TextField(blank=True, db_column='rom', null=True)),
                ('sim', models.TextField(blank=True, db_column='sim', null=True)),
                ('battery', models.TextField(blank=True, db_column='battery', null=True)),
                ('gia', models.IntegerField(blank=True, db_column='price', null=True)),
                ('danhgia', models.TextField(blank=True, db_column='danhgia', null=True)),
                ('soluong', models.IntegerField(blank=True, db_column='sluong', null=True)),
                ('link', models.TextField(blank=True, db_column='link', null=True)),
            ],
            options={
                'db_table': 'datadaloc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dt5',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='name', null=True)),
                ('brand', models.TextField(blank=True, db_column='brand', null=True)),
                ('display', models.TextField(blank=True, db_column='display', null=True)),
                ('hdh', models.TextField(blank=True, db_column='hdh', null=True)),
                ('camera_sau', models.TextField(blank=True, db_column='camera_sau', null=True)),
                ('camera_truoc', models.TextField(blank=True, db_column='camera_truoc', null=True)),
                ('chip', models.TextField(blank=True, db_column='chip', null=True)),
                ('ram', models.TextField(blank=True, db_column='ram', null=True)),
                ('rom', models.TextField(blank=True, db_column='rom', null=True)),
                ('sim', models.TextField(blank=True, db_column='sim', null=True)),
                ('battery', models.TextField(blank=True, db_column='battery', null=True)),
                ('gia', models.IntegerField(blank=True, db_column='price', null=True)),
                ('danhgia', models.TextField(blank=True, db_column='danhgia', null=True)),
                ('soluong', models.IntegerField(blank=True, db_column='sluong', null=True)),
                ('link', models.TextField(blank=True, db_column='link', null=True)),
            ],
            options={
                'db_table': 'dienthoaiall',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='dt3',
            table='dienthoai3',
        ),
    ]
